version: 0.2

env:
  variables:
    NEXT_PUBLIC_API_URL: "http://note-app-backend-prod.eba-ptegrpxd.ap-northeast-2.elasticbeanstalk.com/api"

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - node -v && npm -v
      - cd frontend && npm ci

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - cd ..
      - mkdir -p deploy-frontend
      - cp -r frontend/.next deploy-frontend/
      - cp frontend/package.json deploy-frontend/
      - cp frontend/package-lock.json deploy-frontend/
      - cp frontend/Procfile deploy-frontend/
      - '[ -f frontend/next.config.ts ] && cp frontend/next.config.ts deploy-frontend/ || true'
      - '[ -d frontend/public ] && cp -r frontend/public deploy-frontend/ || true'
      - '[ -d frontend/.ebextensions ] && cp -r frontend/.ebextensions deploy-frontend/ || true'

artifacts:
  files:
    - '**/*'
  base-directory: deploy-frontend
  discard-paths: no
